### ISSUE TITLE
CLion doesn't have Run -> Install option

### ISSUE THREAD

**Issue by jassler** [kigster/cmake-project-template#2]
Maybe I'm just stupid and looking into the wrong menu, but the [README.md](https://github.com/kigster/cmake-project-template/blob/master/README.md#building-in-clion) says the following:

> Select menu option **Run ➜ Build**, and then **Run ➜ Install**.

However, those are the only options shown when I open the project for the first time:

<img width="890" alt="Screen Shot 2019-04-17 at 6 35 57 PM" src="https://user-images.githubusercontent.com/24298790/56325631-e0dea680-6140-11e9-99e4-11f357dcba24.png">

I got the application running after some clicking around, so I just wanted to give a heads up and suggest to change this part of the readme.

**Comment by kigster** [comment]
README says **Build → Build Project**, and **Build → Install**.
